name: grafica
channels:
  - conda-forge
  - defaults
dependencies:
  - mkl
  - numpy
  - pip
  - pyopengl
  - python
  - mesa
  - trimesh
  - networkx
  - pillow
  - matplotlib
  - scipy
  - pip:
    - pyglet>=2.0.0